version: "3.9"
networks:
  app_network:
    driver: bridge
services:
  postgresdb:
    container_name: postgres_env_local_tiximax
    build:
      context: ./StackLaravel
      dockerfile: database.env.local.Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tiximaxnkd1996
      - POSTGRES_DATABASE=tiximax
    ports:
      - 5431:5432
    networks:
      - app_network
    volumes:
      - saved_data:/var/lib/postgresql/data
      - ./DatabaseBackup:/DatabaseBackup
    restart: always
volumes:
  saved_data:
# docker compose -p env_local_my_tiximax down  && docker image prune -a -f && docker builder prune -a -f && docker compose -p env_local_my_tiximax -f docker-compose.env.local.yaml up -d
# docker exec postgres_env_local_tiximax sh  -c "psql -U root -tc \"select 1 from pg_database where datname='tiximax'\" | grep -q 1 || psql -U root -c \"create database tiximax"\"
# docker exec postgres_env_local_tiximax sh -c "psql -c \"select datname from pg_database\" ";
# docker exec postgres_env_local_tiximax sh -c "psql -c \"drop database tiximax\" ";
# docker exec postgres_env_local_tiximax sh  -c "psql -U root -tc \"select 1 from pg_database where datname='tiximax'\" | grep -q 1 || psql -U root -c \"create database tiximax"\"
# docker exec -it postgres_env_local_tiximax /bin/bash
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump --authenticationDatabase admin --username root --password tiximaxnkd1996 --db tiximax --archive > ./DatabaseBackup/tiximax-2025-04-24-23h30.tar.gz
# mongorestore --authenticationDatabase admin --username root --password tiximaxnkd1996 --db tiximax --archive < ./DatabaseBackup/tiximax-2025-04-24-23h30.tar.gz
# pg_dump   -h 0.0.0.0    -p 5432   -U root   -d tiximax    -f ./DatabaseBackup/env.local.tiximax-20251214-23h40.tar.gz
# psql    -U root     -p 5432     -d tiximax    <   ../DatabaseBackup/env.local.tiximax-20251214-23h40.tar.gz
# eas build --platform android --profile local_apk --local
# psql -U root -c "select datname from pg_database";
# docker compose -p env_local_my_tiximax down  && docker image prune -a -f && docker builder prune -a -f && docker volume rm env_local_my_tiximax_saved_data
