version: "3.9"
networks:
  app_network:
    driver: bridge
services:
  nginx:
    container_name: nginx_env_production_tiximax
    ports:
      - 2512:80
    build:
      context: ./ReactVite
      dockerfile: frontend.env.production.Dockerfile
    volumes:
      - ./nginx/default.env.production.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
  postgresdb:
    container_name: postgres_env_production_tiximax
    build:
      context: ./StackLaravel
      dockerfile: database.env.production.Dockerfile
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tiximaxnkd1996
      - POSTGRES_DATABASE=tiximax
    expose:
      - 5432
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./DatabaseBackup:/DatabaseBackup
    restart: always
  backend:
    container_name: backend_env_production_tiximax
    build:
      context: ./StackLaravel
      dockerfile: backend.env.production.Dockerfile
    ports:
      - 7575:8000
    networks:
      - app_network
volumes:
  postgres_data:
# docker compose -p env_production_my_tiximax down && docker image prune -a -f && docker builder prune -a -f && docker compose -p env_production_my_tiximax -f docker-compose.env.production.yaml up -d
# docker exec postgres_env_production_tiximax sh  -c "psql -U root -tc \"select 1 from pg_database where datname='tiximax'\" | grep -q 1 || psql -U root -c \"create database tiximax"\"
# docker exec postgres_env_production_tiximax sh -c "psql -c \"select datname from pg_database\" ";
# docker exec postgres_env_production_tiximax sh -c "psql -c \"drop database tiximax\" ";
# docker exec -it postgres_env_production_tiximax /bin/bash
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
# mongodump --authenticationDatabase admin --username root --password tiximaxnkd1996 --db tiximax --archive > ./DatabaseBackup/tiximax-2025-04-24-23h30.tar.gz
# mongorestore --authenticationDatabase admin --username root --password tiximaxnkd1996 --db tiximax --archive < ./DatabaseBackup/tiximax-2025-04-24-23h30.tar.gz
# pg_dump   -h 0.0.0.0    -p 5432   -U root   -d tiximax    -f ./DatabaseBackup/tiximax-20251211-00h23.tar.gz
# psql    -h 0.0.0.0    -p 5432   -U root   -d tiximax    <   ./DatabaseBackup/tiximax-20251212-15h37.tar.gz
# eas build --platform android --profile production_apk --production
# psql -U root -c "select datname from pg_database";
# docker compose -p env_production_my_tiximax down  && docker image prune -a -f && docker builder prune -a -f && docker volume rm env_production_my_tiximax_postgres_data
